/**
 * The dataset is committed, generated, and re-generated by a script that talks
 * to somebody else's WordPress install. These assertions are what stands
 * between an upstream change and a silently broken deploy — a renumbered
 * taxonomy, a store that loses its coordinates, two farms colliding on a slug
 * and quietly sharing a URL.
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const ORCHARDS = JSON.parse(
  readFileSync(new URL('../src/data/orchards.json', import.meta.url), 'utf8'),
)

const KNOWN_TAGS = new Set([
  'pick_your_own', 'farm_market', 'fresh_cider', 'craft_cider',
  'heirloom', 'gift_boxes', 'greenmarket',
])

// The day-trip radius the importer clips to.
const BOX = { south: 40.40, west: -76.50, north: 42.90, east: -71.80 }

test('there is a usable number of orchards', () => {
  // A drop to near-zero means the upstream endpoint changed shape and the
  // importer wrote an empty file over a good one.
  assert.ok(ORCHARDS.length > 120, `only ${ORCHARDS.length} orchards`)
})

test('slugs are unique, because a slug is a URL', () => {
  const seen = new Set()
  for (const o of ORCHARDS) {
    assert.ok(!seen.has(o.slug), `duplicate slug: ${o.slug}`)
    seen.add(o.slug)
  }
})

test('slugs are URL-safe', () => {
  for (const o of ORCHARDS) {
    assert.match(o.slug, /^[a-z0-9-]+$/, `${o.name} has slug "${o.slug}"`)
  }
})

test('every orchard has a name and a real position inside the box', () => {
  for (const o of ORCHARDS) {
    assert.ok(o.name && o.name.trim().length > 0, `${o.id} has no name`)
    assert.ok(Number.isFinite(o.lat) && Number.isFinite(o.lng), `${o.name} has no position`)
    assert.ok(
      o.lat >= BOX.south && o.lat <= BOX.north && o.lng >= BOX.west && o.lng <= BOX.east,
      `${o.name} is outside the day-trip box at ${o.lat},${o.lng}`,
    )
  }
})

test('tags are all known', () => {
  // Catches a renumbered taxonomy upstream, which would otherwise show up as
  // filters that quietly match nothing.
  for (const o of ORCHARDS) {
    for (const t of o.tags) {
      assert.ok(KNOWN_TAGS.has(t), `${o.name} carries unknown tag "${t}"`)
    }
  }
})

test('no orchard is a greenmarket stall and nothing else', () => {
  // 51 of these were dropped on import: a folding table on a Manhattan
  // pavement is a fact about the grower, not a place to drive to.
  for (const o of ORCHARDS) {
    assert.ok(
      !(o.tags.length === 1 && o.tags[0] === 'greenmarket'),
      `${o.name} is a greenmarket stall and should not be on the map`,
    )
  }
})

test('provenance travels with every row', () => {
  // Two sources with genuinely different terms, which is the reason the
  // licence is a column rather than a line in a README: withdrawing one is a
  // filter, and nobody has to remember which rows came from where.
  const LICENCES = {
    nyaa: 'unstated',
    // Connecticut's apple marketing board states no licence either. Recorded
    // the same way as New York's: as ambiguity, not as permission.
    ctapples: 'unstated',
    osm: 'ODbL-1.0',
    user: 'user-submitted',
  }
  for (const o of ORCHARDS) {
    assert.ok(o.import_source in LICENCES, `${o.name}: unknown source ${o.import_source}`)
    assert.ok(o.import_id, `${o.name} has no import id`)
    assert.equal(o.import_licence, LICENCES[o.import_source], `${o.name}`)
  }
})

test('OSM rows carry no guessed categories', () => {
  // OSM has nothing that maps onto the association's categories. Inferring
  // pick_your_own from a name containing "U-Pick" is exactly the sort of
  // guess that puts a family in a car, so these arrive empty except where
  // craft=cider says so outright.
  for (const o of ORCHARDS.filter((x) => x.import_source === 'osm')) {
    for (const t of o.tags) {
      assert.equal(t, 'craft_cider', `${o.name} has an inferred tag: ${t}`)
    }
  }
})

test('coverage is honest about being uneven', () => {
  // New York remains the bulk. Connecticut now has a real source of its own,
  // so the ratio has moved — but if NY ever stops being the majority it means
  // an importer has gone wrong, not that a state caught up overnight.
  const ny = ORCHARDS.filter((o) => o.state === 'NY').length
  assert.ok(ny > ORCHARDS.length * 0.6, `NY is ${ny} of ${ORCHARDS.length}`)
})

test('every state with real coverage has a source that can be named', () => {
  // The point of the licence column: a state's rows should never be a mystery.
  const bySource = new Map()
  for (const o of ORCHARDS) {
    const key = `${o.state}/${o.import_source}`
    bySource.set(key, (bySource.get(key) ?? 0) + 1)
  }
  for (const [key, n] of bySource) {
    const [, source] = key.split('/')
    assert.ok(source, `${n} rows in ${key} have no source`)
  }
})

test('websites are absolute https URLs when present', () => {
  for (const o of ORCHARDS) {
    if (!o.website) continue
    assert.doesNotThrow(() => new URL(o.website), `${o.name}: ${o.website}`)
    assert.match(o.website, /^https?:\/\//)
  }
})

test('enough orchards have a website for the scraper to be worth writing', () => {
  const withSite = ORCHARDS.filter((o) => o.website).length
  assert.ok(withSite > 100, `only ${withSite} have a website`)
})
