/**
 * The dataset is committed, generated, and re-generated by a script that talks
 * to somebody else's WordPress install. These assertions are what stands
 * between an upstream change and a silently broken deploy — a renumbered
 * taxonomy, a store that loses its coordinates, two farms colliding on a slug
 * and quietly sharing a URL.
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const ORCHARDS = JSON.parse(
  readFileSync(new URL('../src/data/orchards.json', import.meta.url), 'utf8'),
)

const KNOWN_TAGS = new Set([
  'pick_your_own', 'farm_market', 'fresh_cider', 'craft_cider',
  'heirloom', 'gift_boxes', 'greenmarket',
])

// The day-trip radius the importer clips to.
const BOX = { south: 40.40, west: -76.50, north: 42.90, east: -71.80 }

test('there is a usable number of orchards', () => {
  // A drop to near-zero means the upstream endpoint changed shape and the
  // importer wrote an empty file over a good one.
  assert.ok(ORCHARDS.length > 120, `only ${ORCHARDS.length} orchards`)
})

test('slugs are unique, because a slug is a URL', () => {
  const seen = new Set()
  for (const o of ORCHARDS) {
    assert.ok(!seen.has(o.slug), `duplicate slug: ${o.slug}`)
    seen.add(o.slug)
  }
})

test('slugs are URL-safe', () => {
  for (const o of ORCHARDS) {
    assert.match(o.slug, /^[a-z0-9-]+$/, `${o.name} has slug "${o.slug}"`)
  }
})

test('every orchard has a name and a real position inside the box', () => {
  for (const o of ORCHARDS) {
    assert.ok(o.name && o.name.trim().length > 0, `${o.id} has no name`)
    assert.ok(Number.isFinite(o.lat) && Number.isFinite(o.lng), `${o.name} has no position`)
    assert.ok(
      o.lat >= BOX.south && o.lat <= BOX.north && o.lng >= BOX.west && o.lng <= BOX.east,
      `${o.name} is outside the day-trip box at ${o.lat},${o.lng}`,
    )
  }
})

test('tags are all known', () => {
  // Catches a renumbered taxonomy upstream, which would otherwise show up as
  // filters that quietly match nothing.
  for (const o of ORCHARDS) {
    for (const t of o.tags) {
      assert.ok(KNOWN_TAGS.has(t), `${o.name} carries unknown tag "${t}"`)
    }
  }
})

test('no orchard is a greenmarket stall and nothing else', () => {
  // 51 of these were dropped on import: a folding table on a Manhattan
  // pavement is a fact about the grower, not a place to drive to.
  for (const o of ORCHARDS) {
    assert.ok(
      !(o.tags.length === 1 && o.tags[0] === 'greenmarket'),
      `${o.name} is a greenmarket stall and should not be on the map`,
    )
  }
})

test('provenance travels with every row', () => {
  // Two sources with genuinely different terms, which is the reason the
  // licence is a column rather than a line in a README: withdrawing one is a
  // filter, and nobody has to remember which rows came from where.
  const LICENCES = {
    nyaa: 'unstated',
    // Connecticut's apple marketing board and Pennsylvania's PA Preferred
    // both state no licence either. Recorded the same way as New York's: as
    // ambiguity, not as permission.
    ctapples: 'unstated',
    papreferred: 'unstated',
    osm: 'ODbL-1.0',
    user: 'user-submitted',
  }
  for (const o of ORCHARDS) {
    assert.ok(o.import_source in LICENCES, `${o.name}: unknown source ${o.import_source}`)
    assert.ok(o.import_id, `${o.name} has no import id`)
    assert.equal(o.import_licence, LICENCES[o.import_source], `${o.name}`)
  }
})

test('every source in the data has a name to credit', () => {
  /*
   * The "Listed by" row on every orchard page used to be the hardcoded string
   * "New York Apple Association", so 39 Connecticut farms, 14 Pennsylvania
   * ones and 10 OpenStreetMap rows were all credited to an association with no
   * connection to them — and OSM's ODbL requires attribution as a condition of
   * use, so that one was a licence breach rather than a cosmetic error.
   *
   * Read out of sources.ts rather than imported, because node:test cannot load
   * TypeScript. If that file stops being the thing the pages read from, this
   * test is measuring nothing — which is what the assertion on the count of
   * parsed keys is for.
   */
  const source = readFileSync(new URL('../src/lib/sources.ts', import.meta.url), 'utf8')
  const keys = new Set([...source.matchAll(/^\s*key: '([a-z]+)',$/gm)].map((m) => m[1]))
  assert.ok(keys.size >= 4, `parsed ${keys.size} source keys from sources.ts`)

  for (const o of ORCHARDS) {
    assert.ok(
      keys.has(o.import_source),
      `${o.name} is listed by "${o.import_source}", which sources.ts cannot name — ` +
      `it would be credited by its raw key`,
    )
  }
})

test('OSM rows carry no guessed categories', () => {
  // OSM has nothing that maps onto the association's categories. Inferring
  // pick_your_own from a name containing "U-Pick" is exactly the sort of
  // guess that puts a family in a car, so these arrive empty except where
  // craft=cider says so outright.
  for (const o of ORCHARDS.filter((x) => x.import_source === 'osm')) {
    for (const t of o.tags) {
      assert.equal(t, 'craft_cider', `${o.name} has an inferred tag: ${t}`)
    }
  }
})

test('coverage is honest about being uneven', () => {
  // New York remains the bulk. Connecticut now has a real source of its own,
  // so the ratio has moved — but if NY ever stops being the majority it means
  // an importer has gone wrong, not that a state caught up overnight.
  const ny = ORCHARDS.filter((o) => o.state === 'NY').length
  assert.ok(ny > ORCHARDS.length * 0.6, `NY is ${ny} of ${ORCHARDS.length}`)
})

test('every state with real coverage has a source that can be named', () => {
  // The point of the licence column: a state's rows should never be a mystery.
  const bySource = new Map()
  for (const o of ORCHARDS) {
    const key = `${o.state}/${o.import_source}`
    bySource.set(key, (bySource.get(key) ?? 0) + 1)
  }
  for (const [key, n] of bySource) {
    const [, source] = key.split('/')
    assert.ok(source, `${n} rows in ${key} have no source`)
  }
})

test('websites are absolute https URLs when present', () => {
  for (const o of ORCHARDS) {
    if (!o.website) continue
    assert.doesNotThrow(() => new URL(o.website), `${o.name}: ${o.website}`)
    assert.match(o.website, /^https?:\/\//)
  }
})

test('enough orchards have a website for the scraper to be worth writing', () => {
  const withSite = ORCHARDS.filter((o) => o.website).length
  assert.ok(withSite > 100, `only ${withSite} have a website`)
})

test('a field credited to another source names one we can name', () => {
  /*
   * Provenance is per row, and a row can have two sources. Rose's Berry Farm
   * is an OpenStreetMap listing whose address, town and phone come from the
   * Connecticut board — so its page must credit the board for those and OSM
   * for the rest, rather than letting the row's label take credit for work
   * another source did.
   *
   * Anything recorded here has to be nameable for the same reason the row's
   * own source does: an unnameable source has nowhere honest to sit.
   */
  const source = readFileSync(new URL('../src/lib/sources.ts', import.meta.url), 'utf8')
  const keys = new Set([...source.matchAll(/^\s*key: '([a-z]+)',$/gm)].map((m) => m[1]))

  const FIELDS = new Set([
    'name', 'geog', 'address', 'town', 'state', 'zip', 'phone', 'website', 'tags',
  ])

  for (const o of ORCHARDS) {
    for (const [field, from] of Object.entries(o.field_sources ?? {})) {
      assert.ok(FIELDS.has(field), `${o.name}: field_sources names "${field}", not a roster field`)
      assert.ok(keys.has(from), `${o.name}: ${field} credited to "${from}", which sources.ts cannot name`)
      assert.notEqual(
        from, o.import_source,
        `${o.name}: ${field} is recorded as coming from its own source, which says nothing`,
      )
    }
  }
})

test('the add form can name every state the map already shows', () => {
  /*
   * The form sent a hardcoded 'NY' with every submission until it was given a
   * list to choose from, and a list is only a fix while it keeps up with the
   * data. The direction matters: this does NOT require every offered state to
   * have listings — a state with none is exactly the one whose first farm is
   * worth hearing about — only that nothing already on the map is unsayable.
   *
   * Read as text rather than imported: `src/lib/states.ts` is pulled in by a
   * .tsx component, and this file is plain node.
   */
  const source = readFileSync(new URL('../src/lib/states.ts', import.meta.url), 'utf8')
  const offered = new Set([...source.matchAll(/code: '([A-Z]{2})'/g)].map((m) => m[1]))
  assert.ok(offered.size > 0, 'found no states in states.ts — the regex has gone stale')

  for (const o of ORCHARDS) {
    if (!o.state) continue
    assert.ok(
      offered.has(o.state),
      `${o.name} is in ${o.state}, which the add form cannot offer — add it to src/lib/states.ts`,
    )
  }
})
