#!/usr/bin/env node
/**
 * Turn the committed dataset into SQL.
 *
 *   node scripts/seed-to-sql.mjs > supabase/seed.sql
 *   node scripts/db.mjs file supabase/seed.sql
 *
 * Emitting SQL rather than inserting directly means the seed can be written,
 * reviewed and committed without a database to hand — which matters because
 * the static site is the product and the database is an addition to it. Phase
 * 1 shipped with no Supabase project at all.
 *
 * Upserts on (import_source, import_id), so re-running after a fresh import
 * updates rather than duplicating. It deliberately does NOT touch the operator
 * or visitor fact columns: those are earned by scraping and by people going,
 * and a re-seed must never quietly wipe them back to null.
 */
import { readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const read = (f) => JSON.parse(readFileSync(join(ROOT, 'src', 'data', f), 'utf8'))

const orchards = read('orchards.json')
const varieties = read('varieties.json')

/** Postgres string literal. Everything here is generated, never user input,
 *  but quoting properly is the habit that survives the one time it is not. */
const q = (v) =>
  v === null || v === undefined || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}'`

const arr = (values, cast) =>
  values.length === 0
    ? `'{}'::${cast}[]`
    : `array[${values.map(q).join(', ')}]::${cast}[]`

const num = (v) => (v === null || v === undefined ? 'null' : String(v))

const out = []

out.push(`-- Generated by scripts/seed-to-sql.mjs. Do not edit by hand.`)
out.push(`-- ${orchards.length} orchards, ${varieties.length} varieties.`)
out.push(`set search_path = public, extensions;`)
out.push(``)
out.push(`begin;`)
out.push(``)

out.push(`-- The apple vocabulary.`)
for (const v of varieties) {
  out.push(
    `insert into varieties (slug, name, flavour, profile, best_for, hint, start_doy, end_doy, harvest_source, import_source, import_licence) values (` +
      [
        q(v.slug), q(v.name), q(v.flavour),
        arr(v.profile ?? [], 'text'), arr(v.best_for ?? [], 'text'),
        q(v.hint), num(v.start_doy), num(v.end_doy),
        q(v.harvest_source), q(v.import_source), q(v.import_licence),
      ].join(', ') +
      `) on conflict (slug) do update set ` +
      `name = excluded.name, flavour = excluded.flavour, profile = excluded.profile, ` +
      `best_for = excluded.best_for, hint = excluded.hint, ` +
      `start_doy = excluded.start_doy, end_doy = excluded.end_doy, ` +
      `harvest_source = excluded.harvest_source;`,
  )
}

out.push(``)
out.push(`-- Orchards. Note the update list: it carries the roster fields only.`)
out.push(`-- Operator and visitor facts are earned, and a re-seed must not wipe them.`)
for (const o of orchards) {
  out.push(
    `insert into orchards (slug, name, geog, address, town, state, zip, phone, website, tags, import_source, import_id, import_licence) values (` +
      [
        q(o.slug), q(o.name),
        `st_point(${o.lng}, ${o.lat})::geography`,
        q(o.address), q(o.town), q(o.state), q(o.zip), q(o.phone), q(o.website),
        arr(o.tags ?? [], 'orchard_tag'),
        q(o.import_source), q(o.import_id), q(o.import_licence),
      ].join(', ') +
      `) on conflict (import_source, import_id) do update set ` +
      `name = excluded.name, geog = excluded.geog, address = excluded.address, ` +
      `town = excluded.town, state = excluded.state, zip = excluded.zip, ` +
      `phone = excluded.phone, website = excluded.website, tags = excluded.tags;`,
  )
}

out.push(``)
out.push(`commit;`)
out.push(``)

process.stdout.write(out.join('\n'))
process.stderr.write(
  `\n${orchards.length} orchards and ${varieties.length} varieties as SQL\n`,
)
